### ISSUE TITLE
Install fails on Ruby 3.3

### ISSUE THREAD

**Issue by mvz** [gjtorikian/selma#36]
Installing selma 0.2.0 fails for me with Ruby 3.3 with the following error:

```
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Stable API is needed but could not find a candidate. Try enabling the `stable-api-compiled-fallback` feature in rb-sys."', /home/matijs/.cargo/registry/src/github.com-1ecc6299db9ec823/rb-sys-0.9.82/build/main.rs:64:59
```

**Comment by gjtorikian** [comment]
Similar to https://github.com/gjtorikian/commonmarker/issues/268#issuecomment-1876000050, one shouldn't need to compile anything when installing this package. However, I, too, am getting a build error when working in my local repo. 🤔
