### ISSUE TITLE
0.2.{1.2} missing ruby platform gem?

### ISSUE THREAD

**Issue by yob** [gjtorikian/selma#39]
The Gemfile.lock in our application was created ~8 years ago, and it has:

```
PLATFORMS
  ruby
```

We have engineers running `x86_64-linux` and ` arm64-darwin`, and production+ ci runs on `x86_64-linux`.

It seems like bundler is picking gem versions based on the ruby platform, but then quietly on each platform installs the architecture specific version of a gem when they're available.

When we run `bundle update selma` then, bundler is picking `0.2.0` - the most recent version published for the ruby platform. We're unable to get bundler to pick `0.2.2`, which we're interested in for ruby `3.3` compatibility.

Is it possible to publish ruby platform gems for `0.2.1` and `0.2.2`?

**Comment by yob** [comment]
we discovered a workaround: manually editing the `Gemfile.lock` and changing `0.2.0` to `0.2.2` works ok. When we then `bundle install` on `x86_64-linux` and `arm64-darwin`, the appropriate platform specific `0.2.2` gem is used.

**Comment by gjtorikian** [comment]
Sorry about that; I just published 0.2.2 for a bare `ruby` platform.

Just as a head's up, you are probably aware of this already, but I would recommending adding all of your org's supported platforms into bundler directly, with `bundle lock –add-platform`. For example, my app's looks like this:

```
PLATFORMS
  arm64-darwin-22
  arm64-darwin-23
  x86_64-linux
```

It seems that more and more Ruby gem authors are moving to prepackaged binaries (yay!), which means you can save a bunch of time not having to `compile native extensions` by just grabbing the gem necessary for your platform.

**Comment by yob** [comment]
Thanks.

Interestingly, it seems like bundler might have special behaviour when the
only platform in the lock file is Ruby?

With a platform of Ruby and no Ruby version of 0.2.2 published, manually
editing the lock file to specify 0.2.2 resulted in the Linux specific gem
being downloaded on my machine. No compilation happened. 🤷‍♂️

**Comment by gjtorikian** [comment]
Oh, strange. I wonder if that's worth reporting. TBH I've never tried `platform: ruby` myself. 🤷‍♂️
