### ISSUE TITLE
Segfault due to garbage collection

### ISSUE THREAD

**Issue by jordandcarter** [gjtorikian/selma#81]
Noticed some segmentation faults in production, narrowed the issue to selma gem. Seems to happen very rarely until turning on `GC.stress = true` which causes it to always segfault.

I managed to create a failing test here https://github.com/gjtorikian/selma/pull/80

I'll try a workaround of using `GC.disable` around the call to the gem, that seems to avoid the segfault locally.

**Comment by gjtorikian** [comment]
Can you share more about how you’re specifically using Selma (how are you initializing it, what do your selectors look like), or any of the failing text ?

**Comment by jordandcarter** [comment]
Did the test not fail for you? I thought that would be enough sorry, we're using it basically like the test is written. I can't share the specific failing text we ran into in prod. We first thought it was the size of the text being processed, or something specific to the text, but once I turned on `GC.stress = true` before the `Selma::Rewriter.new(...).rewrite(html)` it would segfault on all text.
